// Sample Data for Resources
const resources = {
    "Textbooks": [
        { name: "Fundamentals of Civil Engineering", link: "https://www.pdfdrive.com/fundamentals-of-civil-engineering-e158591550.html" },
        { name: "Structural Analysis", link: "https://www.pdfdrive.com/structural-analysis-and-design-e158591832.html" },
        { name: "Geotechnical Engineering", link: "https://www.pdfdrive.com/geotechnical-engineering-e158591761.html" },
        { name: "Hydrology and Hydraulics", link: "https://www.pdfdrive.com/hydrology-and-hydraulics-e158591897.html" },
        { name: "Transportation Engineering", link: "https://www.pdfdrive.com/transportation-engineering-e158591900.html" },
        { name: "Construction Management", link: "https://www.pdfdrive.com/construction-management-e158591827.html" },
        { name: "Bridge Engineering", link: "https://www.pdfdrive.com/bridge-engineering-e158591928.html" },
        { name: "Reinforced Concrete Design", link: "https://www.pdfdrive.com/reinforced-concrete-design-e158591876.html" },
        { name: "Steel Structures", link: "https://www.pdfdrive.com/steel-structures-e158591873.html" },
        { name: "Environmental Engineering", link: "https://www.pdfdrive.com/environmental-engineering-e158591884.html" },
        { name: "Foundation Engineering", link: "https://www.pdfdrive.com/foundation-engineering-e158591836.html" },
        { name: "Highway Engineering", link: "https://www.pdfdrive.com/highway-engineering-e158591794.html" },
        { name: "Finite Element Analysis", link: "https://www.pdfdrive.com/finite-element-analysis-e158591873.html" },
        { name: "Water Resources Engineering", link: "https://www.pdfdrive.com/water-resources-engineering-e158591846.html" },
        { name: "Surveying and Levelling", link: "https://www.pdfdrive.com/surveying-and-levelling-e158591752.html" },
        { name: "Building Materials", link: "https://www.pdfdrive.com/building-materials-e158591757.html" },
        { name: "Structural Dynamics", link: "https://www.pdfdrive.com/structural-dynamics-e158591764.html" },
        { name: "Earthquake Engineering", link: "https://www.pdfdrive.com/earthquake-engineering-e158591790.html" },
        { name: "Advanced Soil Mechanics", link: "https://www.pdfdrive.com/advanced-soil-mechanics-e158591827.html" },
        { name: "Pavement Analysis and Design", link: "https://www.pdfdrive.com/pavement-analysis-and-design-e158591835.html" }
    ],
    "Journals": [
        { name: "Journal of Civil Engineering", link: "https://www.sciencedirect.com/journal/journal-of-civil-engineering" },
        { name: "International Journal of Concrete Structures", link: "https://www.springer.com/journal/40069" },
        { name: "Journal of Structural Engineering", link: "https://ascelibrary.org/journal/jstruct" },
        { name: "ASCE Civil Engineering Journal", link: "https://ascelibrary.org/journal/civeng" },
        { name: "Journal of Bridge Engineering", link: "https://ascelibrary.org/journal/jbrgeq" },
        { name: "Journal of Construction Engineering and Management", link: "https://ascelibrary.org/journal/jcemd4" },
        { name: "Geotechnical Engineering Journal", link: "https://www.tandfonline.com/journal/tgeo20" },
        { name: "Journal of Hydraulic Engineering", link: "https://ascelibrary.org/journal/jhyeng" },
        { name: "International Journal of Geo-Engineering", link: "https://link.springer.com/journal/40940" },
        { name: "Journal of Water Resources Planning and Management", link: "https://ascelibrary.org/journal/jwrmd5" },
        { name: "Journal of Transportation Engineering", link: "https://ascelibrary.org/journal/jtrte6" },
        { name: "Journal of Environmental Engineering", link: "https://ascelibrary.org/journal/enveng" },
        { name: "Journal of Earthquake Engineering", link: "https://www.tandfonline.com/journal/teee20" },
        { name: "International Journal of Pavement Engineering", link: "https://www.tandfonline.com/journal/tpav20" },
        { name: "Journal of Sustainable Cement-Based Materials", link: "https://www.tandfonline.com/journal/tscb20" },
        { name: "Journal of Advanced Concrete Technology", link: "https://www.jstage.jst.go.jp/browse/jact" },
        { name: "Journal of Structural Fire Engineering", link: "https://www.emerald.com/insight/publication/issn/2040-2317" },
        { name: "Journal of Sustainable Infrastructure", link: "https://www.springer.com/journal/40940" },
        { name: "International Journal of Structural Stability and Dynamics", link: "https://www.worldscientific.com/worldscinet/ijss" },
        { name: "Journal of Advanced Transportation", link: "https://www.hindawi.com/journals/jat/" }
    ],
    "AI Tools": [
        { name: "AI Tool for Structural Design", link: "https://www.autodesk.com/products/revit/overview" },
        { name: "Machine Learning for Civil Engineering", link: "https://www.springer.com/gp/book/9783030518148" },
        { name: "Civil Engineering AI Predictor", link: "https://www.ai-for-civil-engineering.com" },
        { name: "Structural Optimization AI", link: "https://www.ansys.com/products/structures/ansys-structural-optimization" },
        { name: "AI-Based Site Analysis Tool", link: "https://www.geosystems.com/site-analysis" },
        { name: "Automated Quantity Takeoff", link: "https://www.cadsoft.com/quantity-takeoff" },
        { name: "Geotechnical Data AI Analysis", link: "https://www.geosystems.com/ai-analysis" },
        { name: "Traffic Flow Prediction AI", link: "https://www.traffic-ai.com" },
        { name: "Bridge Safety Monitoring AI", link: "https://www.bridge-ai-monitoring.com" },
        { name: "Smart City Planning AI", link: "https://www.smartcity-planning-ai.com" },
        { name: "Pavement Condition Prediction AI", link: "https://www.pavement-ai.com" },
        { name: "Reinforced Concrete Design AI", link: "https://www.ai-concrete-design.com" },
        { name: "Building Information Modeling AI", link: "https://www.bim-ai-tools.com" },
        { name: "Hydrology Prediction AI", link: "https://www.hydrology-ai.com" },
        { name: "AI-Driven Construction Risk Management", link: "https://www.construction-risk-ai.com" },
        { name: "Earthquake Impact Assessment AI", link: "https://www.earthquake-ai.com" },
        { name: "AI for Construction Equipment Optimization", link: "https://www.construction-equipment-ai.com" },
        { name: "Sustainable Construction AI Tool", link: "https://www.sustainable-construction-ai.com" },
        { name: "Deep Learning for Structural Health Monitoring", link: "https://www.structural-health-monitoring-ai.com" },
        { name: "AI for Environmental Impact Assessment", link: "https://www.environmental-impact-ai.com" }
    ],
    "Other Resources": [
        { name: "Civil Engineering Resources Hub", link: "https://www.civilengineeringhub.com" },
        { name: "Online Civil Engineering Courses", link: "https://www.coursera.org/courses?query=civil%20engineering" },
        { name: "Civil Engineering Forum", link: "https://www.engineering-forum.com" },
        { name: "Concrete Design Tutorials", link: "https://www.concrete-tutorials.com" },
        { name: "Engineering Software Downloads", link: "https://www.engineering-software-downloads.com" },
        { name: "Free Civil Engineering Books", link: "https://www.free-engineering-books.com/civil-engineering" },
        { name: "Structural Engineering Library", link: "https://www.structural-engineering-library.com" },
        { name: "Geotechnical Engineering Online Resources", link: "https://www.geotechnical-engineering-resources.com" },
        { name: "Bridge Engineering Resources", link: "https://www.bridge-engineering-resources.com" },
        { name: "Civil Engineering Calculators", link: "https://www.civil-engineering-calculators.com" },
        { name: "Pavement Design Resources", link: "https://www.pavement-design-resources.com" },
        { name: "Hydraulics and Hydrology Resources", link:
